MODEL:
  WEIGHTS: "detectron2://COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml"
  ROI_HEADS:
    NUM_CLASSES: 3  
SOLVER:
  IMS_PER_BATCH: 2
  BASE_LR: 0.001
  MAX_ITER: 1000
OUTPUT_DIR: "./output"